version: '3'

services:
  api:
    build: .
    volumes:
      - .:/api
      - /api/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run dev 
    depends_on:
      - mongo
  mongo:
    image: mongo:4 
    ports:
      - 27017:27017 
    volumes:
      - ./.mongo-data:/data/db
